=== NCIP/taverna-grid/servicewrapper-wsdl-ncbiblast/src/main/xsd/ApplicationResult.xsd
<?xml version="1.0"?>
<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.ebi.ac.uk/schema"
			xmlns="http://www.ebi.ac.uk/schema"
			elementFormDefault="qualified"
			attributeFormDefault="unqualified"
			version="1.1"
			xml:lang="en">
	<xs:annotation>
		<xs:documentation>
			XML Schema for Fasta3, WU-Blast2, NCBI-Blast,... xml results at the EBI
			September 02, 2004	- Version 1.0 - Initial Release
			August 11, 2004 	- Version 0.1 - Initial Version			
		</xs:documentation>
	</xs:annotation>
			
<xs:complexType name="tHeader">
	<xs:sequence>
       <xs:element name="program" 		type="tProgram" 	minOccurs="1" maxOccurs="1"/>
       <xs:element name="commandLine" 	type="tCmdLine" 	minOccurs="0" maxOccurs="1"/>
       <xs:element name="parameters" 	type="tParameters" 	minOccurs="1" maxOccurs="1"/>
       <xs:element name="timeInfo" 		type="tTimeInfo" 	minOccurs="0" maxOccurs="1"/>
     </xs:sequence>
</xs:complexType>

<xs:complexType name="tProgram"> 
	<xs:attribute name="name" 		type="xs:string" use="required"/>
	<xs:attribute name="version" 	type="xs:string" use="required"/>
	<xs:attribute name="citation" 	type="xs:string" use="optional">
		<xs:annotation>
			<xs:documentation> The citation takes the PMID</xs:documentation>
		</xs:annotation>
	</xs:attribute>
</xs:complexType>

<xs:complexType name="tCmdLine">
	<xs:attribute name="command" type="xs:string" use="required"/>
</xs:complexType>



<xs:complexType name="tParameters">
	<xs:all>
		<xs:element name="sequences"		type="tSequences"		minOccurs="1" maxOccurs="1"/>
		<xs:element name="databases" 		type="tDatabases" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="matrix" 			type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="ktup" 			type="xs:int" 	 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="sort" 			type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="scores" 			type="xs:int" 			minOccurs="0" maxOccurs="1"/>
		<xs:element name="strand" 			type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="filter" 			type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="histogram" 		type="xs:boolean" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="alignments" 		type="xs:int" 			minOccurs="0" maxOccurs="1"/>
		<xs:element name="statistics" 		type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="gapOpen" 			type="xs:float" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="gapExtension" 	type="xs:float" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="sequenceRange" 	type="tRange" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="databaseRange" 	type="tRange" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="moleculeType" 	type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="expectationUpper" type="xs:string" 		minOccurs="0" maxOccurs="1"/>
		<xs:element name="expectationLower" type="xs:string" 		minOccurs="0" maxOccurs="1"/>
	</xs:all>
</xs:complexType>

<xs:simpleType name="tRange">
	<xs:restriction base="xs:string">
			<xs:pattern value="\d+\-\d*"/>
		</xs:restriction>
	</xs:simpleType>

<xs:complexType name="tSequences">
	<xs:sequence>
		<xs:element name="sequence" type="tSequence" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="total" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="tSequence">
	<xs:attribute name="number" type="xs:int" use="required"/>
	<xs:attribute name="name" 	type="xs:string" use="optional"/>
	<xs:attribute name="type" 	type="xs:string" use="required"/>
	<xs:attribute name="length" type="xs:int" use="required"/>
</xs:complexType>


<xs:complexType name="tDatabases">
	<xs:sequence>	
		<xs:element name="database" type="tDatabase" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="total" 	type="xs:int" use="required"/>
	<xs:attribute name="sequences" 	type="xs:long" use="required"/>
	<xs:attribute name="letters" 	type="xs:long" use="required"/>
</xs:complexType>

<xs:complexType name="tDatabase">
	<xs:attribute name="number" type="xs:int" use="required"/>
	<xs:attribute name="name" 	type="xs:string" use="required"/>
	<xs:attribute name="type" 	type="xs:string" use="required"/>
	<xs:attribute name="created" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="tTimeInfo">
	<xs:attribute name="start" 	type="xs:dateTime" use="required"/>
	<xs:attribute name="end" 	type="xs:dateTime" use="required"/>
	<xs:attribute name="search" type="xs:duration" use="required"/>
</xs:complexType>

<xs:complexType name="tIterations">
	<xs:sequence>
		<xs:element name="iteration" type="tIteration" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="total" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="tIteration">
	<xs:sequence>
		<xs:element name="hits" type="tHits" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="number" type="xs:int" use="required"/>	
</xs:complexType>

<xs:complexType name="tHits">
	<xs:sequence>
		<xs:element name="hit" type="tHit" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="total" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="tHit">
	<xs:sequence>
		<xs:element name="alignments" type="tAlignments" minOccurs="1" maxOccurs="1"/>	
	</xs:sequence>
	<xs:attribute name="number" 	type="xs:int" 		use="required"/>
	<xs:attribute name="database" 	type="xs:string" 	use="required"/>
	<xs:attribute name="id" 		type="xs:string" 	use="required"/>
	<xs:attribute name="ac" 		type="xs:string" 	use="optional"/>
	<xs:attribute name="length" 	type="xs:long" 		use="optional"/>
	<xs:attribute name="description" type="xs:string" 	use="optional"/>
</xs:complexType>

<xs:complexType name="tAlignments">
	<xs:sequence>
		<xs:element name="alignment" type="tAlignment" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="total" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="tAlignment">
	<xs:all>
		<xs:element name="initn" 		type="xs:int" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="init1" 		type="xs:int" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="opt" 	 		type="xs:int" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="zScore" 		type="xs:float" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="bits" 		type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="expectation" 	type="xs:double" minOccurs="0" maxOccurs="1"/>
		<xs:element name="smithWatermanScore" 	type="xs:int" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="identity" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="overlap" 		type="xs:string" 	minOccurs="0" maxOccurs="1"/>
		<xs:element name="querySeq" 	type="tQuerySeq" minOccurs="1" maxOccurs="1"/>
		<xs:element name="pattern" 		type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="matchSeq" 	type="tMatchSeq" minOccurs="1" maxOccurs="1"/>
		<xs:element name="score" 		type="xs:int" minOccurs="0" maxOccurs="1"/>
		<xs:element name="probability" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="positives" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="gaps" 		type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="match" 		type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ungapped" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="strand" 		type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="frame"               type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="queryMatch" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="predNumber" 	type="xs:float" minOccurs="0" maxOccurs="1"/>
		<xs:element name="matches" 		type="xs:int" minOccurs="0" maxOccurs="1"/>
		<xs:element name="conservative" type="xs:int" minOccurs="0" maxOccurs="1"/>
		<xs:element name="mismatches" 		type="xs:int" minOccurs="0" maxOccurs="1"/>
		<xs:element name="indels" 		type="xs:int" minOccurs="0" maxOccurs="1"/>
	</xs:all>
	<xs:attribute name="number" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="tQuerySeq">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="start" 	type="xs:int" use="required"/>
			<xs:attribute name="end" 	type="xs:int" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="tMatchSeq">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="start" 	type="xs:int" use="required"/>
			<xs:attribute name="end" 	type="xs:int" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="tSSSR">
	<xs:choice>
    	<xs:element name="iterations" type="tIterations"  maxOccurs="1"/>
        <xs:element name="hits" type="tHits" maxOccurs="1"/>
    </xs:choice>
</xs:complexType>

<xs:element name="EBIApplicationResult">
	<xs:complexType>
		<xs:all>
        	<xs:element name="Header" type="tHeader" minOccurs="1" maxOccurs="1"/>
        	<xs:element name="SequenceSimilaritySearchResult" type="tSSSR"/>
       	</xs:all>
	</xs:complexType>
</xs:element>

<xs:element name="EBIApplicationError" type="xs:string"/>

</xs:schema>

=== NCIP/taverna-grid/servicewrapper/servicewrapper-invoker-ncbiblast/src/main/resources/uk/org/mygrid/cagrid/servicewrapper/serviceinvoker/ncbiblast/ncbi_output.xml
<?xml version="1.0"?>
<EBIApplicationResult xmlns="http://www.ebi.ac.uk/schema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.ebi.ac.uk/schema/ApplicationResult.xsd">
<Header>
    <program name="NCBI-blastp" version="2.2.17 [Aug-26-2007]" citation="PMID:9254694"/>
    <commandLine command="/ebi/extserv/bin/ncbi-blast/blastall -p blastp
-d $IDATA_CURRENT/blastdb/uniprot -i /ebi/extserv/blast-work/interactive/
/blast-20081216-1227145899.input -M BLOSUM62
-b 50 -v 50 -e 1.0 -X 0 -G 11 -E 1 -a 16 -L 1,137 -m 0 -gt -F F -C F "/>
    <parameters>
        <sequences total="1">
            <sequence number="1" name="Sequence" type="p" length="137"/>
        </sequences>
        <databases total="1" sequences="7226283" letters="2365401343">
            <database number="1" name="uniprot" type="p"
                      created="2008-11-25T00:14:00+00:00"/>
        </databases>
        <gapOpen>11</gapOpen>
        <gapExtension>1</gapExtension>
    </parameters>
</Header>
<SequenceSimilaritySearchResult>
    <hits total="2">
        <hit number="1" database="uniprot" id="WAP_RAT" ac="P01174" length="137"
description="Whey acidic protein OS=Rattus norvegicus GN=Wap PE=1 SV=2">
            <alignments total="1">
                <alignment number="1">
                    <score>763</score>
                    <bits>298</bits>
                    <expectation>8e-80</expectation>
                    <identity>100</identity>
                    <positives>100</positives>
                    <querySeq start="1" end="137">MRCSISLVLGLLALEVALARNLQEHVFNSVQSMCSDDSFSEDTECINCQTNEECAQNDMCCPSSCGRSCKTPVNIEVQKAGRCPWNPIQMIAAGPCPKDNPCSIDSDCSGTMKCCKNGCIMSCMDPEPKSPTVISFQ</querySeq>
                    <pattern>MRCSISLVLGLLALEVALARNLQEHVFNSVQSMCSDDSFSEDTECINCQTNEECAQNDMCCPSSCGRSCKTPVNIEVQKAGRCPWNPIQMIAAGPCPKDNPCSIDSDCSGTMKCCKNGCIMSCMDPEPKSPTVISFQ</pattern>
                    <matchSeq start="1" end="137">MRCSISLVLGLLALEVALARNLQEHVFNSVQSMCSDDSFSEDTECINCQTNEECAQNDMCCPSSCGRSCKTPVNIEVQKAGRCPWNPIQMIAAGPCPKDNPCSIDSDCSGTMKCCKNGCIMSCMDPEPKSPTVISFQ</matchSeq>
                </alignment>
            </alignments>
        </hit>
        <hit number="2" database="uniprot" id="Q3UQ94_MOUSE" ac="Q3UQ94" length="140"
description="Putative uncharacterized protein OS=Mus musculus GN=Wap PE=2 SV=1">
            <alignments total="1">
                <alignment number="1">
                    <score>465</score>
                    <bits>183</bits>
                    <expectation>3e-45</expectation>
                    <identity>66</identity>
                    <positives>75</positives>
                    <querySeq start="1" end="134">MRCSISLVLGLLALEVALARNLQEHVFNSVQSMCSDDSFSEDTECINCQTNEECAQNDMCCPSSCGRSCKTPVNIEVQKAGRCPWNPIQMIAA-GPCPKDNPCSIDSDCSGTMKCCKNGCIMSCMDPEPKSPTVI</querySeq>
                    <pattern>MRC ISLVLGLLALEVALA+NL+E VFNSVQSM    S  ETECI CQTNEECAQN MCCP SCGR+ KTPVNI V KAG CPWN +QMI++ GPCP    CS D +CSG MKCC   C+M+C  P P+  ++I
</pattern>
                    <matchSeq start="1" end="135">MRCLISLVLGLLALEVALAQNLEEQVFNSVQSMFPKASPIEGTECIICQTNEECAQNAMCCPGSCGRTRKTPVNIGVPKAGFCPWNLLQMISSTGPCPMKIECSSDRECSGNMKCCNVDCVMTCTPPVPEVWSII</matchSeq>
                </alignment>
            </alignments>
        </hit>
</hits>
</SequenceSimilaritySearchResult>
</EBIApplicationResult>
