=== NCIP/taverna-grid/servicewrapper-service-interproscan/schema/InterProScan/InterProScanResult.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.ebi.ac.uk/schema"
  xmlns="http://www.ebi.ac.uk/schema"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  version="1.0"
  xml:lang="en">
<xs:annotation>
<xs:documentation>XML Schema for InterProScan XML results at the
EBI.</xs:documentation>
</xs:annotation>

<xs:complexType name="tDatabase">
  <xs:attribute name="number" type="xs:int" use="required" />
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="type" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="tDatabases">
  <xs:sequence>
    <xs:element name="database" type="tDatabase" minOccurs="1"
maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="total" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="tSequences">
  <xs:attribute name="total" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="tParameters">
  <xs:sequence>
    <xs:element name="sequences" type="tSequences" minOccurs="1"
maxOccurs="1" />
    <xs:element name="databases" type="tDatabases" minOccurs="1"
maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="tProgram">
  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="version" type="xs:string" use="required"/>
  <xs:attribute name="citation" type="xs:string" use="optional">
    <xs:annotation>
      <xs:documentation>PubMed identifier for
citation</xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:complexType>

<xs:complexType name="tHeader">
  <xs:sequence>
    <xs:element name="program" type="tProgram" minOccurs="1" maxOccurs="1"
/>
    <xs:element name="parameters" type="tParameters" minOccurs="1"
maxOccurs="1"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="tRelRef">
  <xs:attribute name="ipr_ref" type="xs:string" />
</xs:complexType>

<xs:complexType name="tFoundIn">
  <xs:sequence>
    <xs:element name="rel_ref" type="tRelRef" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="tClassification">
  <xs:sequence>
    <xs:element name="category" type="xs:string" />
    <xs:element name="description" type="xs:string" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:string" />
  <xs:attribute name="class_type" type="xs:string" />
</xs:complexType>

<xs:complexType name="tMatch">
  <xs:sequence>
    <xs:element name="location" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
	<xs:attribute name="start" type="xs:int" />
	<xs:attribute name="end" type="xs:int" />
	<xs:attribute name="score" type="xs:string" />
	<xs:attribute name="status" type="xs:string" />
	<xs:attribute name="evidence" type="xs:string" />
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="id" type="xs:string" />
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="dbname" type="xs:string" />
</xs:complexType>

<xs:complexType name="tInterPro">
  <xs:sequence>
    <xs:element name="child_list" minOccurs="0" maxOccurs="1">
      <xs:complexType>
	<xs:sequence>
	  <xs:element name="rel_ref" type="tRelRef" minOccurs="1"
maxOccurs="unbounded" />
	</xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="found_in" minOccurs="0" maxOccurs="1">
      <xs:complexType>
	<xs:sequence>
	  <xs:element name="rel_ref" type="tRelRef" minOccurs="1"
maxOccurs="unbounded" />
	</xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="contains" minOccurs="0" maxOccurs="1">
      <xs:complexType>
	<xs:sequence>
	  <xs:element name="rel_ref" type="tRelRef" minOccurs="1"
maxOccurs="unbounded" />
	</xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="classification" type="tClassification" minOccurs="0"
maxOccurs="unbounded" />
    <xs:element name="match" type="tMatch" minOccurs="1"
maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:string" />
  <xs:attribute name="name" type="xs:string" />
  <xs:attribute name="type" type="xs:string" />
  <xs:attribute name="parent_id" type="xs:string" />
</xs:complexType>

<xs:complexType name="tProtein">
  <xs:sequence>
    <xs:element name="interpro" type="tInterPro" minOccurs="0"
maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:string" />
  <xs:attribute name="length" type="xs:string" />
  <xs:attribute name="crc64" type="xs:string" />
</xs:complexType>

<xs:complexType name="tInterProMatches">
  <xs:sequence>
    <xs:element name="protein" type="tProtein" minOccurs="0"
maxOccurs="unbounded" />
  </xs:sequence>
</xs:complexType>

<xs:element name="EBIInterProScanResults">
  <xs:complexType>
    <xs:all>
      <xs:element name="Header" type="tHeader" minOccurs="1" maxOccurs="1"
/>
      <xs:element name="interpro_matches" type="tInterProMatches"
minOccurs="1" maxOccurs="1" />
    </xs:all>
  </xs:complexType>
</xs:element>

</xs:schema>

=== NCIP/taverna-grid/servicewrapper-invoker-interproscan/src/main/resources/uk/org/mygrid/cagrid/servicewrapper/serviceinvoker/interproscan/wap_rat_output.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<EBIInterProScanResults xmlns="http://www.ebi.ac.uk/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ebi.ac.uk/schema/InterProScanResult.xsd">
        <Header>
                <program name="InterProScan" version="4.0" citation="PMID:11590104" />
                <parameters>
                        <sequences total="1" />
                        <databases total="14">
                                <database number="1" name="PRODOM" type="sequences" />
                                <database number="2" name="PANTHER" type="model" />
                                <database number="3" name="GENE3D" type="model" />
                                <database number="4" name="PIR" type="model" />
                                <database number="5" name="PFAM" type="model" />
                                <database number="6" name="SMART" type="model" />
                                <database number="7" name="TIGRFAMs" type="model" />
                                <database number="8" name="PRINTS" type="matrix" />
                                <database number="9" name="PROSITE" type="strings" />
                                <database number="10" name="PROSITE" type="strings" />
                                <database number="11" name="PROFILE" type="strings" />
                                <database number="12" name="SUPERFAMILY" type="model" />
                                <database number="13" name="SIGNALP" type="model" />
                                <database number="14" name="TMHMM" type="model" />
                        </databases>
                </parameters>
        </Header>
<interpro_matches>

   <protein id="sp|P01174|WAP_RAT" length="137" crc64="1C2E8ADA9FD97949" >
        <interpro id="IPR008197" name="Whey acidic protein, 4-disulphide core" type="Domain" parent_id="IPR015874">
          <contains>
            <rel_ref ipr_ref="IPR018069"/>
          </contains>
          <match id="G3DSA:4.10.75.10" name="no description" dbname="GENE3D">
            <location start="77" end="128" score="9.5e-05" status="T" evidence="Gene3D" />
          </match>
          <match id="PF00095" name="WAP" dbname="PFAM">
            <location start="30" end="72" score="7.4e-05" status="T" evidence="HMMPfam" />
            <location start="79" end="126" score="1.1e-12" status="T" evidence="HMMPfam" />
          </match>
          <match id="SM00217" name="WAP" dbname="SMART">
            <location start="79" end="127" score="2.4e-22" status="T" evidence="HMMSmart" />
          </match>
          <match id="SSF57256" name="Elafin-like" dbname="SUPERFAMILY">
            <location start="77" end="128" score="1.8e-10" status="T" evidence="superfamily" />
            <location start="47" end="74" score="0.004" status="T" evidence="superfamily" />
          </match>
        </interpro>
        <interpro id="IPR015874" name="4-disulphide core" type="Domain">
          <child_list>
            <rel_ref ipr_ref="IPR008197"/>
          </child_list>
          <contains>
            <rel_ref ipr_ref="IPR018069"/>
          </contains>
          <match id="PR00003" name="4DISULPHCORE" dbname="PRINTS">
            <location start="76" end="85" score="1.2e-07" status="T" evidence="FPrintScan" />
            <location start="101" end="108" score="1.2e-07" status="T" evidence="FPrintScan" />
            <location start="108" end="117" score="1.2e-07" status="T" evidence="FPrintScan" />
            <location start="118" end="126" score="1.2e-07" status="T" evidence="FPrintScan" />
          </match>
        </interpro>
        <interpro id="IPR018069" name="Whey acidic protein, 4-disulphide core, conserved site" type="Conserved_site">
          <found_in>
            <rel_ref ipr_ref="IPR008197"/>
            <rel_ref ipr_ref="IPR015874"/>
         </found_in>
          <match id="PS00317" name="4_DISULFIDE_CORE" dbname="PROSITE">
            <location start="48" end="61" score="NA" status="T" evidence="PatternScan" />
            <location start="102" end="115" score="NA" status="T" evidence="PatternScan" />
          </match>
          <match id="PS00317" name="4_DISULFIDE_CORE" dbname="PROSITE">
            <location start="48" end="61" score="NA" status="?" evidence="ScanRegExp" />
            <location start="102" end="115" score="8e-5" status="T" evidence="ScanRegExp" />
          </match>
        </interpro>
        <interpro id="noIPR" name="unintegrated" type="unintegrated">
          <match id="PTHR19441" name="WHEY ACDIC PROTEIN (WAP)" dbname="PANTHER">
            <location start="4" end="133" score="3.5e-34" status="T" evidence="HMMPanther" />
          </match>
          <match id="SignalP" name="signal-peptide" dbname="SIGNALP">
            <location start="1" end="19" score="NA" status="?" evidence="SignalPHMM" />
          </match>
        </interpro>
   </protein>

</interpro_matches>
</EBIInterProScanResults>
